name: blog.gladis.org
description: Stuff I don't want to look up anymore
url: http://blog.gladis.org
# markdown: redcarpet
# highlighter: pygments
paginate: 10
paginate_path: "/page:num"
future: false
gems: [jekyll-paginate]
